#배포 버전, for production

version: '3.7'

services:
#react 컨테이너
    client:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        tty: true
        ports:
            - "3000:3000"
        volumes: 
            - ./frontend:/app
            - /app/node_modules
        networks:
            - app-tier
#db 컨테이너
    mongodb:
        image: mongo
        container_name: mongo
        ports:
            - "27017:27017"
        restart: unless-stopped
        command: mongod --auth
        env_file:
            - ./settings/prod/.env.db
        volumes:
            - mongodbdata:/data/db
        networks:
            - app-tier
#flask 컨테이너
    api:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        command: gunicorn -w 1 -b 0.0.0.0:5000 server:app --reload
        ports:
            - "5000:5000"
        volumes:
            - appdata:/var/www/
        links:
            - mongodb:mongodb   
        depends_on: 
            - mongodb
        env_file:
            - ./settings/prod/.env.prod
        networks:
            - app-tier
#nginx 컨테이너
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "8000:8000"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - client
            - api
        networks:
            - app-tier
        restart: "on-failure"
        
#redis컨테이너     
    redis:
        image: redis:latest
        container_name: redis
        hostname: redis_dev
        
networks:
    app-tier:
        driver: bridge
volumes:
    mongodbdata:
    appdata:
